"""Increase password_hash length

Revision ID: 17200235c5c9
Revises: 97ed79cbd822
Create Date: 2025-06-29 10:40:18.518377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17200235c5c9'
down_revision = '97ed79cbd822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
